### ISSUE TITLE
noarch?

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/smif-feedstock#15]
Should this package be a noarch package?

It seems to be pure Python.

**Comment by tomalrussell** [comment]
I think it could be noarch, it's definitely pure Python.

Does it matter that we skip building on Python <3.5 and 32bit Windows? (Looking at https://conda-forge.org/docs/meta.html#building-noarch-packages)

**Comment by SylvainCorlay** [comment]
Hum did not know about that. Although there is a paragraph:

*Note that while noarch: python does not work with selectors, it does work with version constraints, so skip: True  # [py2k] can sometimes be replaced with a constrained python version in the build/run subsections: say python >=3 instead of just python.*

**Comment by tomalrussell** [comment]
That should cover the Python version, if I read it right.

I think the reason for skipping 32bit Windows is just that we depend on [pyarrow](https://anaconda.org/conda-forge/pyarrow) which is only 64bit.

**Comment by SylvainCorlay** [comment]
conda-forge does not support 32bit windows though :)

**Comment by tomalrussell** [comment]
Closed by #17 - we're now noarch, with python >=3.5
